### ISSUE TITLE
generate_dataset error!

### ISSUE THREAD

**Issue by ricabreu** [sthiemichen/ergam#1]
Hi,
I run your examples in the R.3.2.3 version for Linux and R.3.4.2 version for windows, and they stoped when the "generate_dataset" was request! It's a bug or another issue?

Ricardo

**Comment by sthiemichen** [comment]
Hi Ricardo,

what examples are you exactly referring to? The function `generate_dataset()` is internal and therefore not exported (the examples for the internal functions are also not intended to be used directly, they are mainly just for internal documentation). 
I've just checked the examples for the ergam function itself and they are working using R 3.4.2 on Linux, so the internal call to `generate_dataset()` works.

If you want to use that function call it with `ergam:::generate_dataset()`.

Does that help?

Best regards,
Stephanie

**Comment by ricabreu** [comment]
Hi Stephanie,
I couldn´t work with this package following your paper "Stable exponential random graph models with non-parametric components for large dense networks".

I have a large network (~4000 nodes w/ 56k edges)  and i used diferent packages (ergm, hergm..) for fit it but the result were in vain....  My hope is yours procedement. Maybe my R knowledge is not suficent.. :(

Thanks & best regards,
Ricardo
